# 4. Copies and Views

A slicing operation creates a view on the original array, which is just a way of accessing array data. Thus the original array is not copied in memory. You can use **np.may_share_memory()** to check if two arrays share the same memory block. 

**When modifying the view, the original array is modified as well:**

In [2]:
import numpy as np

In [3]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
b = a[::2]
b

array([0, 2, 4, 6, 8])

In [5]:
np.shares_memory(a, b)

True

In [6]:
b[0] = 10
b

array([10,  2,  4,  6,  8])

In [7]:
a  #eventhough we modified b,  it updated 'a' because both shares same memory

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [8]:


a = np.arange(10)

c = a[::2].copy()     #force a copy
c

array([0, 2, 4, 6, 8])

In [9]:
np.shares_memory(a, c)

False

In [10]:
c[0] = 10

a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])