# 5. Fancy Indexing

NumPy arrays can be indexed with slices, but also with boolean or integer arrays **(masks)**. This method is called **fancy indexing**. It creates copies not views.

**Using Boolean Mask**

In [2]:
import numpy as np

In [3]:
a = np.random.randint(0, 20, 15)
a

array([11,  1, 11,  8,  7, 16,  0,  2, 15,  7, 16,  2,  7,  0,  5])

In [4]:
mask = (a % 2 == 0)

In [5]:
extract_from_a = a[mask]

extract_from_a

array([ 8, 16,  0,  2, 16,  2,  0])

**Indexing with a mask can be very useful to assign a new value to a sub-array:**

In [6]:
a[mask] = -1
a

array([11,  1, 11, -1,  7, -1, -1, -1, 15,  7, -1, -1,  7, -1,  5])

**Indexing with an array of integers**

In [7]:
a = np.arange(0, 100, 10)

a

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [8]:
#Indexing can be done with an array of integers, where the same index is repeated several time:

a[[2, 3, 2, 4, 2]]

array([20, 30, 20, 40, 20])

In [9]:
# New values can be assigned 

a[[9, 7]] = -200

a

array([   0,   10,   20,   30,   40,   50,   60, -200,   80, -200])