# Basic Reductions

**computing sums**

In [3]:
import numpy as np

In [4]:
x = np.array([1, 2, 3, 4])
np.sum(x)

10

In [5]:
#sum by rows and by columns

x = np.array([[1, 1], [2, 2]])
x

array([[1, 1],
       [2, 2]])

In [6]:
x.sum(axis=0)   #columns first dimension

array([3, 3])

In [7]:
x.sum(axis=1)  #rows (second dimension)

array([2, 4])

**Other reductions**

In [8]:
x = np.array([1, 3, 2])
x.min()

1

In [9]:
x.max()

3

In [10]:
x.argmin()# index of minimum element

0

In [11]:
x.argmax()# index of maximum element

1

**Logical Operations**

In [12]:
np.all([True, True, False])

False

In [13]:
np.any([True, False, False])

True

In [14]:
#Note: can be used for array comparisions
a = np.zeros((50, 50))
np.any(a != 0)

False

In [15]:
np.all(a == a)

True

In [16]:
a = np.array([1, 2, 3, 2])
b = np.array([2, 2, 3, 2])
c = np.array([6, 4, 4, 5])
((a <= b) & (b <= c)).all()

True

**Statistics**

In [17]:
x = np.array([1, 2, 3, 1])
y = np.array([[1, 2, 3], [5, 6, 1]])
x.mean()

1.75

In [18]:
np.median(x)

1.5

In [19]:
np.median(y, axis=-1) # last axis

array([2., 5.])

In [20]:
x.std()          # full population standard dev.

0.82915619758885

**Example:**

Data in populations.txt describes the populations of hares and lynxes (and carrots) in northern Canada during 20 years.


In [24]:
#load data into numpy array object
data = np.loadtxt('C:\Practice_Python\populations.txt')

In [25]:
data

array([[ 1900., 30000.,  4000., 48300.],
       [ 1901., 47200.,  6100., 48200.],
       [ 1902., 70200.,  9800., 41500.],
       [ 1903., 77400., 35200., 38200.],
       [ 1904., 36300., 59400., 40600.],
       [ 1905., 20600., 41700., 39800.],
       [ 1906., 18100., 19000., 38600.],
       [ 1907., 21400., 13000., 42300.],
       [ 1908., 22000.,  8300., 44500.],
       [ 1909., 25400.,  9100., 42100.],
       [ 1910., 27100.,  7400., 46000.],
       [ 1911., 40300.,  8000., 46800.],
       [ 1912., 57000., 12300., 43800.],
       [ 1913., 76600., 19500., 40900.],
       [ 1914., 52300., 45700., 39400.],
       [ 1915., 19500., 51100., 39000.],
       [ 1916., 11200., 29700., 36700.],
       [ 1917.,  7600., 15800., 41800.],
       [ 1918., 14600.,  9700., 43300.],
       [ 1919., 16200., 10100., 41300.],
       [ 1920., 24700.,  8600., 47300.]])

In [26]:
year, hares, lynxes, carrots = data.T #columns to variables
print(year)

[1900. 1901. 1902. 1903. 1904. 1905. 1906. 1907. 1908. 1909. 1910. 1911.
 1912. 1913. 1914. 1915. 1916. 1917. 1918. 1919. 1920.]


In [27]:
#The mean population over time
populations = data[:, 1:]
populations

array([[30000.,  4000., 48300.],
       [47200.,  6100., 48200.],
       [70200.,  9800., 41500.],
       [77400., 35200., 38200.],
       [36300., 59400., 40600.],
       [20600., 41700., 39800.],
       [18100., 19000., 38600.],
       [21400., 13000., 42300.],
       [22000.,  8300., 44500.],
       [25400.,  9100., 42100.],
       [27100.,  7400., 46000.],
       [40300.,  8000., 46800.],
       [57000., 12300., 43800.],
       [76600., 19500., 40900.],
       [52300., 45700., 39400.],
       [19500., 51100., 39000.],
       [11200., 29700., 36700.],
       [ 7600., 15800., 41800.],
       [14600.,  9700., 43300.],
       [16200., 10100., 41300.],
       [24700.,  8600., 47300.]])

In [28]:
#sample standard deviations
populations.std(axis=0)

array([20897.90645809, 16254.59153691,  3322.50622558])

In [29]:
#which species has the highest population each year?

np.argmax(populations, axis=1)

array([2, 2, 0, 0, 1, 1, 2, 2, 2, 2, 2, 2, 0, 0, 0, 1, 2, 2, 2, 2, 2],
      dtype=int64)